FROM ruby:2.3.3
MAINTAINER Thiago Soares <thiagosoarescruz0@gmail.com>

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs-legacy mysql-client
RUN mkdir /phalanx
WORKDIR /phalanx

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install --jobs 20 --retry 5
COPY . ./
EXPOSE 3000

ADD Gemfile /phalanx/Gemfile
ADD Gemfile.lock /phalanx/Gemfile.lock
RUN bundle install
ADD . /phalanx

# Configure an entry point, so we don't need to specify
# "bundle exec" for each of our commands.
ENTRYPOINT ["bundle", "exec"]

# The main command to run when the container starts. Also
# tell the Rails dev server to bind to all interfaces by
# default.
CMD ["rails", "server", "-b", "0.0.0.0"]
